#!/usr/bin/env sh

set -e

REVISION=${TRAVIS_BUILD_NUMBER:-0}

scripts/normalizeWhitespace

(
cd server
REVISION=$REVISION ./build
)

if [ $REVISION -gt 0 ]; then
    # Publish only on the node 0.10 Travis CI matric
    # This is less than ideal; I'd rather only publish
    # after all matrixes complete, but I don't know that
    # I can using Travis.  The npm deploy provider wants
    # to have the root directory contain the package.json,
    # and after_success runs on every matrix with the
    # versioned package.json already cleaned up

    NODE_MINOR_VERSION=`node --version | sed -E -e 's/v[0-9]+\.([0-9]+)\.[0-9]+/\1/'`
    if [ ! -f ~/.npmrc -a $NODE_MINOR_VERSION -eq 10 ]; then
        echo "_auth = $NPM_API_KEY" > ~/.npmrc
        echo "email = brandon.byars@gmail.com" >> ~/.npmrc
        echo >> ~/.npmrc
        (
        cd server
        grunt coveralls

        # On Travis Linux machine, npm publish fails with blanket in package.json
        sed -E -e '/blanket/d' -i'' package.json

        npm publish
        )
    fi
fi
