#!/usr/bin/env sh

IS_PUBLISHED_VERSION=`git describe --tags --exact-match 2>/dev/null`

if [ -z "$MB_VERSION" ]; then
    MB_VERSION=`cat package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/'`
fi

# We don't set the version suffix on tagged (published) builds
if [ -n "$CIRCLE_BUILD_NUM" -a -z "$IS_PUBLISHED_VERSION" ]; then
    MB_VERSION="$MB_VERSION-beta.$CIRCLE_BUILD_NUM"
fi

# Pass between workflow jobs
echo "export MB_VERSION=$MB_VERSION" > env.sh
chmod +x env.sh

npm install
MB_SLOW_TEST_TIMEOUT=6000 MB_PORT=3535 MB_VERSION=$MB_VERSION node_modules/grunt-cli/bin/grunt "$@"
