#!/usr/bin/env sh

IS_PUBLISHED_VERSION=`git describe --tags --exact-match 2>/dev/null`

if [ -z "$MB_VERSION" ]; then
    MB_VERSION=`cat package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/'`
fi

# We don't set the version suffix on tagged (published) builds
if [ -n "$TRAVIS_BUILD_NUMBER" -a -z "$IS_PUBLISHED_VERSION" ]; then
    MB_VERSION="$MB_VERSION-beta.$TRAVIS_BUILD_NUMBER"
fi

npm install

MB_PORT=3535 MB_VERSION=$MB_VERSION node_modules/grunt-cli/bin/grunt "$@"
