#!/usr/bin/env sh

if [ -z "$MB_VERSION" ]; then
    MB_VERSION=`cat package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/'`
fi

npm install
MB_SLOW_TEST_TIMEOUT=60000 MB_PORT=3535 MB_VERSION=$MB_VERSION node_modules/grunt-cli/bin/grunt "$@"
