#!/usr/bin/env sh

IS_PUBLISHED_VERSION=$(git describe --tags --exact-match 2>/dev/null)

if [ -z "$MB_VERSION" ]; then
    MB_VERSION=`cat package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/'`
fi

# We don't set the version suffix on tagged (published) builds
if [ -z "$IS_PUBLISHED_VERSION" ]; then
    GIT_SHA=$(git rev-parse --short=8 HEAD)
    MB_VERSION="$MB_VERSION-beta.$GIT_SHA"
fi

npm install
MB_PORT=3535 MB_VERSION=$MB_VERSION MB_SLOW_TEST_TIMEOUT=6000 node_modules/grunt-cli/bin/grunt "$@"
