FROM node:8.11.3

LABEL maintainer Brandon Byars <brandon.byars@gmail.com>

USER node
RUN mkdir /home/node/mountebank
WORKDIR /home/node/mountebank

COPY --chown=node:node releases.json .
COPY --chown=node:node Gruntfile.js .
COPY --chown=node:node tasks ./tasks
COPY --chown=node:node bin ./bin
COPY --chown=node:node performanceTest ./performanceTest
COPY --chown=node:node functionalTest ./functionalTest
COPY --chown=node:node node_modules ./node_modules
COPY --chown=node:node src ./src
COPY --chown=node:node package.json .
