#!/bin/sh

set -e

VERSION=$1

echo "Deploying to Firebase..."

cp firebase.json docs/mountebank/$VERSION

(
cd docs/mountebank/$VERSION
../../../node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --project firebase-mountebank
)
