#!/bin/sh

set -e

PUBLISH=$1

echo "Deploying to npm (PUBLISH=$PUBLISH)..."
(
cd dist/mountebank
if [ "$PUBLISH" = "true" ]; then
    dpl --provider=npm --email=brandon.byars@gmail.com --api-key=$NPM_API_KEY --skip-cleanup
fi
cd ..
)
