#!/bin/sh

set -e

VERSION=$1

echo "Deploying to Firebase..."

npm install -g firebase-tools@^2.1
cp firebase.json docs/mountebank/$VERSION

(
cd docs/mountebank/$VERSION
firebase deploy --token "$FIREBASE_TOKEN"
)
