#!/bin/sh

set -e

# base npm tarball
cd dist
MB_VERSION=$(cat mountebank/package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/')

tar cvf mountebank-v$MB_VERSION-npm.tar.gz mountebank
cd ..

scripts/dist/createSelfContainedTarball linux x86
scripts/dist/createSelfContainedTarball linux x64
scripts/dist/createSelfContainedTarball darwin x64

scripts/dist/createWindowsZip x86
scripts/dist/createWindowsZip x64

if [ $(uname) = 'Darwin' ]; then
    scripts/dist/createPackages darwin osxpkg
    mv dist/mountebank-$MB_VERSION.pkg dist/mountebank-v$MB_VERSION.pkg
elif [ $(uname) = 'Linux' ]; then
    sudo apt-get update
    sudo apt-get install rpm
    scripts/dist/createPackages linux deb
    scripts/dist/createPackages linux rpm
fi
