#!/bin/sh

set -e

MB_VERSION=$(cat dist/mountebank/package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/')
NODE_VERSION=`node -v`

cd dist

for PLATFORM in x86 x64; do
    MB_FILENAME=mountebank-v$MB_VERSION-win$PLATFORM

    if [ "$PLATFORM" = 'x86' ]; then
        URL=http://nodejs.org/dist/$NODE_VERSION/node.exe
    else
        URL=http://nodejs.org/dist/$NODE_VERSION/x64/node.exe
    fi

    [ -e $MB_FILENAME ] && rm -rf $MB_FILENAME
    mkdir $MB_FILENAME

    cd $MB_FILENAME

    wget $URL

    cp -r ../mountebank .

    cd mountebank
    npm install --production
    cd ..

    echo "node.exe mountebank/bin/mb" > ./mb.cmd

    cd ..
    zip -r $MB_FILENAME.zip $MB_FILENAME
done
