#!/bin/sh

echo "Deploying to heroku..."

[ -e dist/heroku ] && rm -rf dist/heroku
cp -R dist/mountebank dist/heroku
cp Procfile dist/heroku

(
cd dist/heroku
dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=mountebank-dev --skip-cleanup
dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=mountebank --skip-cleanup --tags
)
