#!/bin/sh

set -e

echo "Deploying to heroku..."

[ -e dist/heroku ] && rm -rf dist/heroku
cp -R dist/mountebank dist/heroku
cp Procfile dist/heroku

(
cd dist/heroku
dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=mountebank-dev --skip-cleanup

if [ -n "`git describe --tags --exact-match 2>/dev/null`" ]; then
    dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=mountebank --skip-cleanup --strategy=git
fi
cd ..
)
