#!/bin/sh

[ -e dist/s3 ] && rm -rf dist/s3
mkdir dist/s3
cp dist/*.* dist/s3

set -e

echo "Deploying to S3..."
dpl --provider=s3 --access-key-id=AKIAIE2GUJRUIHGE2PWA --secret-access-key=$AWS_ACCESS_KEY \
    --bucket=mountebank --local-dir=dist/s3 --upload-dir=v1.2 --skip-cleanup
