#!/bin/sh

echo "Deploying to npm..."
(
cd dist/mountebank
if [ -n "`git describe --tags --exact-match 2>/dev/null`" ]; then
    dpl --provider=npm --email=brandon.byars@gmail.com --api-key=$NPM_API_KEY --skip-cleanup
fi
cd ..
)
