#!/usr/bin/env node
'use strict';

var thisPackage = require('../package.json'),
    fs = require('fs');

var nodeMajor = process.version.replace(/(v\d+)\..*/, '$1'),
    devDependenciesToReplace = thisPackage.devDependenciesBasedOnNodeVersion[nodeMajor] || {};

Object.keys(devDependenciesToReplace).forEach(function (dep) {
    console.log('Switching ' + dep + ' to ' + devDependenciesToReplace[dep]);
    thisPackage.devDependencies[dep] = devDependenciesToReplace[dep];
});

fs.writeFileSync('package.json', JSON.stringify(thisPackage, null, 2) + '\n');
