#!/usr/bin/env sh

which sh
uname
for FILE in `find . -type f -not \( -path "*/node_modules/*" -o -path "*/.git/*" -o -path "*/.DS_Store" -o -path "*/.idea/*" \)`
do
    # Remove trailing whitespace
    sed -E -e 's/[[:space:]]*$//' -i '' "$FILE"
done

