#!/bin/sh

set -e

if [ `uname` = "Darwin" ]; then
    OS=macosx
else
    OS=linux
fi

VERSION=3.2.0.1227

echo "Downloading sonar-scanner..."
wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${VERSION}-${OS}.zip
unzip sonar-scanner-cli-${VERSION}-${OS}.zip
rm sonar-scanner-cli-${VERSION}-${OS}.zip

# Necessary for sonar-scanner to run correctly
PATH=$PATH:`pwd`/sonar-scanner-${VERSION}-${OS}/bin
echo sonar.host.url=https://sonarqube.com >> sonar-scanner-${VERSION}-${OS}/conf/sonar-scanner.properties

echo "Running sonar-scanner..."
sonar-scanner \
    -Dsonar.projectKey=mountebank \
    -Dsonar.projectName=mountebank \
    -Dsonar.sources=src \
    -Dsonar.tests=test,functionalTest,performanceTest \
    -Dsonar.host.url=https://sonarqube.com \
    -Dsonar.organization=bbyars-github \
    -Dsonar.login=$SONARQUBE_LOGIN

rm -rf sonar-scanner-${VERSION}-${OS}
