#!/bin/sh

set -e

if [ `uname` = "Darwin" ]; then
    OS=macosx
else
    OS=linux
fi

echo "Downloading sonar-scanner..."
wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-${OS}.zip
unzip sonar-scanner-cli-3.0.3.778-${OS}.zip
rm sonar-scanner-cli-3.0.3.778-${OS}.zip

# Necessary for sonar-scanner to run correctly
PATH=$PATH:`pwd`/sonar-scanner-3.0.3.778-${OS}/bin
echo sonar.host.url=https://sonarqube.com >> sonar-scanner-3.0.3.778-${OS}/conf/sonar-scanner.properties

echo "Running sonar-scanner..."
sonar-scanner \
    -Dsonar.projectKey=mountebank \
    -Dsonar.projectName=mountebank \
    -Dsonar.sources=src \
    -Dsonar.tests=test,functionalTest,performanceTest \
    -Dsonar.host.url=https://sonarqube.com \
    -Dsonar.organization=bbyars-github \
    -Dsonar.login=$SONARQUBE_LOGIN

rm -rf sonar-scanner-3.0.3.778-${OS}
