#!/bin/sh


NODE_VERSION=`node -v | sed -E -e 's/(v[0-9]+\.[0-9]+)\.[0-9]+/\1/'`
MB_VERSION=`cat dist/mountebank/package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/'`
IS_PUBLISHED_VERSION=`git describe --tags --exact-match 2>/dev/null`

# We don't set the version suffix on tagged (published) builds
if [ -n "$TRAVIS_BUILD_NUMBER" -a -z "$IS_PUBLISHED_VERSION" ]; then
    MB_VERSION="$MB_VERSION+$TRAVIS_BUILD_NUMBER"
fi

set -e

if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$NODE_VERSION" = "v0.12" ]; then
    gem install dpl

    if [ $(uname) = 'Darwin' ]; then
        scripts/dist/createPackages darwin osxpkg
        mv dist/mountebank-$MB_VERSION.pkg dist/mountebank-v$MB_VERSION.pkg

        scripts/deploy/deployS3
    elif [ $(uname) = 'Linux' ]; then
        node_modules/grunt-cli/bin/grunt coveralls

        # base npm tarball
        cd dist
        tar cvf mountebank-v$MB_VERSION-npm.tar.gz mountebank
        cd ..

        scripts/dist/createSelfContainedTarball linux x86 $MB_VERSION
        scripts/dist/createSelfContainedTarball linux x64 $MB_VERSION
        scripts/dist/createSelfContainedTarball darwin x64 $MB_VERSION

        scripts/dist/createWindowsZip x86 $MB_VERSION
        scripts/dist/createWindowsZip x64 $MB_VERSION

        sudo apt-get update
        sudo apt-get install rpm
        scripts/dist/createPackages linux deb $MB_VERSION
        scripts/dist/createPackages linux rpm $MB_VERSION

        scripts/deploy/deployS3
        scripts/deploy/deployNpm
        scripts/deploy/deployHeroku
    fi
fi
